### ISSUE TITLE
Continuous IOException when WebSocket write fails due to a closed socket

### ISSUE THREAD

**Issue by pvub** [eclipse-vertx/vert.x#2338]
Hi,

We are using version 3.5.0, to build a websocket server. At times, when a client's websocket is closed, the EventLoop is still trying to write to the netty Channel, ignoring the closed state. This might be something internal to netty, but I want to ask your team first to understand if there is any known issue.
A result of this, is repeated IOExeptions being thrown on the ExeptionHandler of the WebSocket.

java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
        at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
        at sun.nio.ch.IOUtil.write(IOUtil.java:148)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
        at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:433)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:875)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:639)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580))

During this time, the application grinds to a halt and the main event loop stops processing other tasks.

This usually happens when the application is writing lots of messages to a client socket, and the socket gets disconnected (while some messages still held in the socket/channel's write queue). I am not familiar with the internal acrchitecture of netty, but it looks like the following code in Netty's AbstractChannel's flush0() method is not closing the channel appropriately causing further writes to happen

            try {
                doWrite(outboundBuffer);
            } catch (Throwable t) {
                if (t instanceof IOException && config().isAutoClose()) {
                    /**
                     * Just call {@link #close(ChannelPromise, Throwable, boolean)} here which will take care of
                     * failing all flushed messages and also ensure the actual close of the underlying transport
                     * will happen before the promises are notified.
                     *
                     * This is needed as otherwise {@link #isActive()} , {@link #isOpen()} and {@link #isWritable()}
                     * may still return {@code true} even if the channel should be closed as result of the exception.
                     */
                    close(voidPromise(), t, FLUSH0_CLOSED_CHANNEL_EXCEPTION, false);
                } else {
                    outboundBuffer.failFlushed(t, true);
                }
            } finally {
                inFlush0 = false;
            }

I am not sure if there is a designated way to properly close vert.x's websocket in order to avoid this.

Thanks in advance.

Udai.

**Comment by vietj** [comment]
can you provide a reproducer ?

**Comment by vietj** [comment]
You should be able to close the websocket from any thread, however I'm asking a reproducer so we can observe the issue as well and find out the issue, without that it's a very speculative thing to do

**Comment by pvub** [comment]
@vietj Here is a simple reproducer. I have a replay server which will just write a message to the socket when a client connects, repeatedly, trying to fill the out queue. After a minute, it will close the socket on a timer. At that time, we'll see repeated "ClosedChannelException". This also happens when we kill the client as well. The idea is to write large amounts of messages that are still pending in netty's pipeline when the socket is closed.

[WSClient.java.zip](https://github.com/eclipse/vert.x/files/1843317/WSClient.java.zip)
[WSReplay.java.zip](https://github.com/eclipse/vert.x/files/1843318/WSReplay.java.zip)
[replay-logging.xml.zip](https://github.com/eclipse/vert.x/files/1843322/replay-logging.xml.zip)

**Comment by vietj** [comment]
will have a look

**Comment by vietj** [comment]
can you share it as a java project with Maven ?

**Comment by pvub** [comment]
Here it is.
[VertxTest.zip](https://github.com/eclipse/vert.x/files/1885351/VertxTest.zip)

**Comment by vietj** [comment]
the project does not compile:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project VertxTest: Compilation failure: Compilation failure: 
[ERROR] /Users/julien/Downloads/VertxTest/src/main/java/com/pvub/vertxtest/WSReplay.java:[3,29] package com.pvub.wsproxy.util does not exist
[ERROR] /Users/julien/Downloads/VertxTest/src/main/java/com/pvub/vertxtest/WSClient.java:[6,29] package com.pvub.wsproxy.util does not exist
```

**Comment by pvub** [comment]
Fixed the compile error. Here is the latest.
[VertxTest.zip](https://github.com/eclipse/vert.x/files/1899338/VertxTest.zip)

**Comment by vietj** [comment]
it still does not compile

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project VertxTest: Compilation failure
[ERROR] /Users/julien/Downloads/VertxTest/src/main/java/com/pvub/vertxtest/WSReplay.java:[48,17] cannot find symbol
[ERROR]   symbol:   method setPerMessageWebsocketCompressionSupported(boolean)
[ERROR]   location: variable httpOpts of type io.vertx.core.http.HttpServerOptions

**Comment by pvub** [comment]
I was using a build off a branch with permessage-deflate compression. I remove that option now, so it should work with mainline. Sorry for the back-and-forth.
[VertxTest.zip](https://github.com/eclipse/vert.x/files/1899509/VertxTest.zip)

**Comment by vietj** [comment]
can you say how to use this reproducer ?

**Comment by pvub** [comment]
I added a log configuration, and now it builds a fat jar. You'll need to run the replay server and client from the same jar.

For the server:
java -Dlog4j.configurationFile=log4j2.xml -jar target/VertxTest-1.0-SNAPSHOT-fat.jar 

For the client:
java -Dlog4j.configurationFile=log4j2.xml -cp target/VertxTest-1.0-SNAPSHOT-fat.jar com.pvub.vertxtest.WSClient

Both on localhost, and be using port 10880. Server just writes a message repeatedly to the client socket, and disconnects once writequeue is full, causing netty to flush resulting in IOException
[VertxTest.zip](https://github.com/eclipse/vert.x/files/1921102/VertxTest.zip)
[VertxTest.zip](https://github.com/eclipse/vert.x/files/1921103/VertxTest.zip)

.

**Comment by pvub** [comment]
@vietj Any luck reproducing the issue?

**Comment by vietj** [comment]
I haven't had time to investigate yet, will give a spin tomorrow.

**Comment by vietj** [comment]
have you tried your reproducer with latest master ?

**Comment by pvub** [comment]
@vietj Haven't tried with master. Will give it a try.

**Comment by vietj** [comment]
thanks let report here

**Comment by vietj** [comment]
I'm getting on the server

```May 04, 2018 9:23:25 AM io.vertx.core.net.impl.ConnectionBase
SEVERE: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3808428071, max: 3817865216)
```

```
2018-05-04 09:23:53.796 | INFO | replay | RxIoScheduler-3 | error= java.lang.IllegalStateException: WebSocket is closed
	at io.vertx.core.http.impl.WebSocketImplBase.checkClosed(WebSocketImplBase.java:253)
	at io.vertx.core.http.impl.WebSocketImplBase.writeQueueFull(WebSocketImplBase.java:92)
	at io.vertx.rxjava.core.http.ServerWebSocket.writeQueueFull(ServerWebSocket.java:96)
	at com.pvub.vertxtest.WSReplay.lambda$replay$10(WSReplay.java:111)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:224)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
```

and

```
Exception in thread "RxIoScheduler-2" May 04, 2018 9:23:11 AM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2560 ms, time limit is 2000
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.StringCoding.encode(StringCoding.java:350)
	at java.lang.String.getBytes(String.java:941)
	at io.vertx.core.buffer.impl.BufferImpl.<init>(BufferImpl.java:56)
	at io.vertx.core.buffer.impl.BufferImpl.<init>(BufferImpl.java:60)
	at io.vertx.core.buffer.impl.BufferFactoryImpl.buffer(BufferFactoryImpl.java:40)
	at io.vertx.core.buffer.Buffer.buffer(Buffer.java:74)
	at io.vertx.core.http.impl.WebSocketImplBase.writeTextMessageInternal(WebSocketImplBase.java:199)
	at io.vertx.core.http.impl.WebSocketImplBase.writeTextMessage(WebSocketImplBase.java:166)
	at io.vertx.rxjava.core.http.ServerWebSocket.writeTextMessage(ServerWebSocket.java:147)
	at com.pvub.vertxtest.WSReplay.lambda$replay$7(WSReplay.java:98)
	at com.pvub.vertxtest.WSReplay$$Lambda$71/1310775681.call(Unknown Source)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:224)2018-05-04 09:23:14.820 | INFO | replay | vert.x-eventloop-thread-0 | Got message Hello world Thu Jan 01 01:00:00 CET 1970 

	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
```

**Comment by vietj** [comment]
the issue you are describing seems to be buffered messages which you should try to avoid (raising GC issues like it does for me) and use WebSocket.writeQueueFull() to stop sending message and resume sending when the drain handler is called.

**Comment by pvub** [comment]
@vietj The issue we constantly run into is a situation where we have to close the socket, and there is no way to clear the buffered messages, before we do so, in order to avoid the netty event loop trying to write to a closed socket.
In prod we do use the writeQueueFull() to figure out if we are adding too much to the socket buffer, but we never ran into memory issue, probably since we are using a bigger heap size.
What we really need is a way to clear any pending buffered data waiting to be written to the socket, before we close it.

**Comment by vietj** [comment]
if you run out of memory it means that you need to slow down the incoming messages according to writeQueueFull() or discard some of them.

I haven't been able to reproduce it... so that does not help
