### ISSUE TITLE
FileResolve shutdown hook throws exception

### ISSUE THREAD

**Issue by sfitts** [eclipse-vertx/vert.x#2692]
I'm shutting down a Vertx environment using `vertx.close`.  During this process the system runs its shutdown hooks.  One of those is deployed by `FileResolver` and it is consistently throw the following exception:

```
java.util.concurrent.RejectedExecutionException: Task io.vertx.core.impl.TaskQueue$$Lambda$62/2067180044@6ab80713 rejected from java.util.concurrent.ThreadPoolExecutor@48cf5273[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 308]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at io.vertx.core.impl.TaskQueue.execute(TaskQueue.java:93)
	at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:293)
	at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:237)
	at io.vertx.core.file.impl.FileSystemImpl$BlockingAction.run(FileSystemImpl.java:839)
	at io.vertx.core.file.impl.FileSystemImpl.deleteRecursive(FileSystemImpl.java:223)
	at io.vertx.core.impl.FileResolver.deleteCacheDir(FileResolver.java:328)
	at io.vertx.core.impl.FileResolver.lambda$setupCacheDir$1(FileResolver.java:317)
	at java.lang.Thread.run(Thread.java:745)
```

The issue is that since we're doing close we've already terminated the executor used to run blocking code so the attempt to queue work is rejected.  It would be better if this exception didn't leak as it does currently since there is essentially nothing the Vert.x programmer can do about it (at least not AFAICT).

**Comment by sfitts** [comment]
Obviously if the exception can be avoided altogether that would be best, but I'm not sure that's possible.

**Comment by vietj** [comment]
yes it happens we should get rid of those

**Comment by vietj** [comment]
I think the problem is that it's because this is executed from a finalizer, so we should find a way to execute this with the current thread or another worker

**Comment by vietj** [comment]
which version is it ?

**Comment by vietj** [comment]
actually this is fixed in master can you check ?

**Comment by sfitts** [comment]
Version was 3.5.3, though it still happens in 3.5.4.  Sorry for logging an already fixed issue, though in my defense the fix did just happen 13 hours ago :).

In any case, the latest version of FileResolver does fix the issue.  Thanks.

**Comment by vietj** [comment]
@sfitts no problem
