### ISSUE TITLE
`RecordParser` issue in Vert.x 3.9.2

### ISSUE THREAD

**Issue by jo5ef** [eclipse-vertx/vert.x#3546]
### Version

3.9.2

### Context

Unfortunately [this commit](https://github.com/eclipse-vertx/vert.x/commit/343e1f9726fb908fd1f80f59047dccffed2c77c8#diff-91372f99f884daaf1678eb0b504efee1) broke something for us after upgrading to 3.9.2. We use a `RecordParser` to parse a chunked http response. The `RecordParser` is trying to re-use the input buffers for parsing but when using ssl, the response buffers returned by netty have their internal `maxCapacity` set to the length of the chunk, which means nothing can be added to these buffers. As a consequence, the following exception occurs:

```
java.lang.IndexOutOfBoundsException: writerIndex(1) + minWritableBytes(1) exceeds maxCapacity(1): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf(ridx: 0, widx: 1, cap: 1/1)
  at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:295)
  at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:282)
  at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1104)
  at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1097)
  at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1088)
  at io.netty.buffer.WrappedByteBuf.writeBytes(WrappedByteBuf.java:780)
  at io.vertx.core.buffer.impl.BufferImpl.appendBuffer(BufferImpl.java:209)
  at io.vertx.core.parsetools.impl.RecordParserImpl.handle(RecordParserImpl.java:283)
  at io.vertx.reactivex.core.parsetools.RecordParser.handle(RecordParser.java:460)
```

### Reproducer

Here is a reproducer that succeeds with Vert.x 3.9.1 but fails with Vert.x 3.9.2:

```java
@Test
public void testRecordParser(TestContext ctx) {
  var o = Observable.fromArray("a", "\n", "b\nc")
    // this is how the buffers are returned from netty in a chunked ssl http response:
    .map(s -> Buffer.buffer(UnpooledByteBufAllocator.DEFAULT.directBuffer(s.length(), s.length())).appendString(s));
    
  RecordParser.newDelimited("\n", o).toObservable()
    .doOnNext(b -> System.out.println("parsed: " + b.toString()))
    .ignoreElements()
    .subscribe(CompletableHelper.toObserver(ctx.asyncAssertSuccess()));
}
```

So in a nutshell the `RecordParser` now expects the buffers that it is given to be *writeable* which was not the case in the previous version. Was that change intentional?

### Other Reproducer

Here's another reproducer that demonstrates how we ran into this issue. The following test also passes with Vert.x 3.9.1 and fails/hangs with Vert.x 3.9.2 (we use H2 but it happens for both protocols):

```java
@RunWith(VertxUnitRunner.class)
public class RecordParserTest {

  private Vertx vertx;
  private int port;

  @Before
  public void setUp(TestContext ctx) {
    vertx = Vertx.vertx();
    vertx.createHttpServer(new HttpServerOptions()
      .setSsl(true)
      .setPemKeyCertOptions(new PemKeyCertOptions()
        // openssl req -x509 -newkey rsa:4096 -nodes -keyout key.pem -out cert.pem -days 365
        .setKeyPath("key.pem")
        .setCertPath("cert.pem")))
      .requestHandler(req -> req.response()
        .setChunked(true)
        .write(Buffer.buffer("a"))
        .write(Buffer.buffer("\n"))
        .write(Buffer.buffer("b\nc"))
        .end())
      .rxListen(0)
      .doOnSuccess(s -> port = s.actualPort())
      .subscribe(SingleHelper.toObserver(ctx.asyncAssertSuccess()));
  }

  @Test
  public void testGet(TestContext ctx) {
    var req = vertx.createHttpClient(new HttpClientOptions()
      .setSsl(true)
      .setTrustAll(true)
      .setDefaultPort(port)).get("/");

    var res = req.toObservable()
      .firstOrError()
      .flatMapObservable(HttpClientResponse::toObservable);

    RecordParser.newDelimited("\n", res).toObservable()
      .doOnNext(b -> System.out.println("received: " + b.toString()))
      .count()
      .doOnSuccess(n -> ctx.assertEquals(3L, n))
      .subscribe(SingleHelper.toObserver(ctx.asyncAssertSuccess()));

    req.end();
  }
}
```

Our workaround for now is to copy the buffers before passing them to the `RecordParser` but I think it'd be better for the `RecordParser` to treat its input as read-only and manage the buffers it needs for parsing internally.

**Comment by vietj** [comment]
thanks @jo5ef

**Comment by vietj** [comment]
I agree with your suggestion about having the record parser manages its own buffers.

I would like also understand why those buffers are not modifiable because normally there are copied and it might be an issue to deal with.

**Comment by vietj** [comment]
from what I see, the actual issue is a consequence of the fact that underlying `ByteBuf` with SSL are not copied because they are not direct. So they can be modified but they can't be added content because they have a max capacity set to actual buffer length.

**Comment by jo5ef** [comment]
Exactly. Although the max capacity is currently not exposed in the Vert.x `Buffer` interface. And of course it'd be nice if the `RecordParser` only creates new buffer slices when it needs to. If the chunks line up perfectly with the parsing for example, buffers can be passed-through.

**Comment by vietj** [comment]
@jo5ef for now I fixed the issue in Vert.x TCP buffer handling - see https://github.com/eclipse-vertx/vert.x/issues/3554 . I tried your example with this fix and it works correctly.

**Comment by jo5ef** [comment]
Excellent, thank you! I'm also very happy with the improvements #3554, #3555, #3556!

**Comment by poryee** [comment]
Hello it seems that the issue might be back. Im using vertx core 4.3.7. I tried moving to latest 4.4.4 but error still persist when im handling large stream of data
